#define MON_JAN (0)
#define MON_FEB (1)
#define MON_MAR (2)
#define MON_APR (3)
#define MON_MAY (4)
#define MON_JUN (5)
#define MON_JUL (6)
#define MON_AUG (7)
#define MON_SEP (8)
#define MON_OCT (9)
#define MON_NOV (10)
#define MON_DEC (11)
#define MON_GTEQ (0)
#define FRI_GTEQ (1)
#define WED_GTEQ (2)
#define TUE_LAST (3)
#define MON_LAST (4)
#define SAT_GTEQ (5)
#define SUN_GTEQ (6)
#define SAT_LAST (7)
#define GIVEN_DAY (8)
#define SUN_LAST (9)
#define FRI_LAST (10)
#define THU_LAST (11)
#define TUE_GTEQ (12)
#define THU_GTEQ (13)
#define WED_LAST (14)
#define ATREF_U (0)
#define ATREF_W (1)
#define ATREF_S (2)
#define RULE_Thule (0)
#define RULE_E_EurAsia (1)
#define RULE_EU (2)
#define RULE_Palestine (3)
#define RULE_Syria (4)
#define RULE_Troll (5)
#define RULE_Cuba (6)
#define RULE_LH (7)
#define RULE_NONE (8)
#define RULE_Moldova (9)
#define RULE_Chatham (10)
#define RULE_Brazil (11)
#define RULE_Zion (12)
#define RULE_AV (13)
#define RULE_Para (14)
#define RULE_AS (15)
#define RULE_EUAsia (16)
#define RULE_Tonga (17)
#define RULE_Jordan (18)
#define RULE_C_Eur (19)
#define RULE_Lebanon (20)
#define RULE_AT (21)
#define RULE_Fiji (22)
#define RULE_NZ (23)
#define RULE_US (24)
#define RULE_E_Eur (25)
#define RULE_Chile (26)
#define RULE_Namibia (27)
#define RULE_WS (28)
#define RULE_Mexico (29)
#define RULE_W_Eur (30)
#define RULE_Morocco (31)
#define RULE_AN (32)
#define RULE_Canada (33)

typedef struct {
       uint8_t name       : 6; // Empirical
       uint8_t month      : 4; // 0...11
       uint8_t daytrig    : 4; // 0...14
       uint8_t daynum     : 5; // 0...31
       uint8_t athr       : 4; // 0..11 
       uint8_t atmin      : 6; // 0..59
       uint8_t atref      : 2; // 0..2
       uint8_t offsethrs  : 2; // 0..2
       uint8_t offsetmins : 6; // 0..59
       char fmtstr[4];     // Empirical, longest is >> average
} rule_t;
static const rule_t rules[] ICACHE_RODATA_ATTR = {
{RULE_AN, MON_APR, SUN_GTEQ, 1, 2, 0, ATREF_S, 0, 0, "S"},
{RULE_AN, MON_OCT, SUN_GTEQ, 1, 2, 0, ATREF_S, 1, 0, "D"},
{RULE_AS, MON_APR, SUN_GTEQ, 1, 2, 0, ATREF_S, 0, 0, "S"},
{RULE_AS, MON_OCT, SUN_GTEQ, 1, 2, 0, ATREF_S, 1, 0, "D"},
{RULE_AT, MON_APR, SUN_GTEQ, 1, 2, 0, ATREF_S, 0, 0, "S"},
{RULE_AT, MON_OCT, SUN_GTEQ, 1, 2, 0, ATREF_S, 1, 0, "D"},
{RULE_AV, MON_APR, SUN_GTEQ, 1, 2, 0, ATREF_S, 0, 0, "S"},
{RULE_AV, MON_OCT, SUN_GTEQ, 1, 2, 0, ATREF_S, 1, 0, "D"},
{RULE_Brazil, MON_OCT, SUN_GTEQ, 15, 0, 0, ATREF_W, 1, 0, "S"},
{RULE_C_Eur, MON_MAR, SUN_LAST, 0, 2, 0, ATREF_S, 1, 0, "S"},
{RULE_C_Eur, MON_OCT, SUN_LAST, 0, 2, 0, ATREF_S, 0, 0, ""},
{RULE_Canada, MON_MAR, SUN_GTEQ, 8, 2, 0, ATREF_W, 1, 0, "D"},
{RULE_Canada, MON_NOV, SUN_GTEQ, 1, 2, 0, ATREF_W, 0, 0, "S"},
{RULE_Chatham, MON_APR, SUN_GTEQ, 1, 2, 45, ATREF_S, 0, 0, "S"},
{RULE_Chatham, MON_SEP, SUN_LAST, 0, 2, 45, ATREF_S, 1, 0, "D"},
{RULE_Chile, MON_AUG, SUN_GTEQ, 9, 4, 0, ATREF_U, 1, 0, "S"},
{RULE_Chile, MON_MAY, SUN_GTEQ, 9, 3, 0, ATREF_U, 0, 0, ""},
{RULE_Cuba, MON_MAR, SUN_GTEQ, 8, 0, 0, ATREF_S, 1, 0, "D"},
{RULE_Cuba, MON_NOV, SUN_GTEQ, 1, 0, 0, ATREF_S, 0, 0, "S"},
{RULE_EU, MON_MAR, SUN_LAST, 0, 1, 0, ATREF_U, 1, 0, "S"},
{RULE_EU, MON_OCT, SUN_LAST, 0, 1, 0, ATREF_U, 0, 0, ""},
{RULE_EUAsia, MON_MAR, SUN_LAST, 0, 1, 0, ATREF_U, 1, 0, "S"},
{RULE_EUAsia, MON_OCT, SUN_LAST, 0, 1, 0, ATREF_U, 0, 0, ""},
{RULE_E_Eur, MON_MAR, SUN_LAST, 0, 0, 0, ATREF_W, 1, 0, "S"},
{RULE_E_Eur, MON_OCT, SUN_LAST, 0, 0, 0, ATREF_W, 0, 0, ""},
{RULE_E_EurAsia, MON_MAR, SUN_LAST, 0, 0, 0, ATREF_W, 1, 0, "S"},
{RULE_E_EurAsia, MON_OCT, SUN_LAST, 0, 0, 0, ATREF_W, 0, 0, ""},
{RULE_Fiji, MON_JAN, SUN_GTEQ, 15, 3, 0, ATREF_W, 0, 0, ""},
{RULE_Fiji, MON_NOV, SUN_GTEQ, 1, 2, 0, ATREF_W, 1, 0, "S"},
{RULE_Jordan, MON_MAR, THU_LAST, 0, 0, 59, ATREF_W, 1, 0, "S"},
{RULE_Jordan, MON_OCT, FRI_LAST, 0, 0, 0, ATREF_S, 0, 0, ""},
{RULE_LH, MON_APR, SUN_GTEQ, 1, 2, 0, ATREF_W, 0, 0, "S"},
{RULE_LH, MON_OCT, SUN_GTEQ, 1, 2, 0, ATREF_W, 0, 30, "D"},
{RULE_Lebanon, MON_MAR, SUN_LAST, 0, 0, 0, ATREF_W, 1, 0, "S"},
{RULE_Lebanon, MON_OCT, SUN_LAST, 0, 0, 0, ATREF_W, 0, 0, ""},
{RULE_Mexico, MON_APR, SUN_GTEQ, 1, 2, 0, ATREF_W, 1, 0, "D"},
{RULE_Mexico, MON_OCT, SUN_LAST, 0, 2, 0, ATREF_W, 0, 0, "S"},
{RULE_Moldova, MON_MAR, SUN_LAST, 0, 2, 0, ATREF_W, 1, 0, "S"},
{RULE_Moldova, MON_OCT, SUN_LAST, 0, 3, 0, ATREF_W, 0, 0, ""},
{RULE_Morocco, MON_JUL, GIVEN_DAY, 2, 2, 0, ATREF_W, 1, 0, "S"},
{RULE_Morocco, MON_MAY, GIVEN_DAY, 21, 3, 0, ATREF_W, 0, 0, ""},
{RULE_NZ, MON_APR, SUN_GTEQ, 1, 2, 0, ATREF_S, 0, 0, "S"},
{RULE_NZ, MON_SEP, SUN_LAST, 0, 2, 0, ATREF_S, 1, 0, "D"},
{RULE_Namibia, MON_APR, SUN_GTEQ, 1, 2, 0, ATREF_W, 0, 0, ""},
{RULE_Namibia, MON_SEP, SUN_GTEQ, 1, 2, 0, ATREF_W, 1, 0, "S"},
{RULE_Palestine, MON_MAR, SAT_LAST, 0, 1, 0, ATREF_W, 1, 0, "S"},
{RULE_Palestine, MON_OCT, SAT_LAST, 0, 1, 0, ATREF_W, 0, 0, ""},
{RULE_Para, MON_MAR, SUN_GTEQ, 22, 0, 0, ATREF_W, 0, 0, ""},
{RULE_Para, MON_OCT, SUN_GTEQ, 1, 0, 0, ATREF_W, 1, 0, "S"},
{RULE_Syria, MON_MAR, FRI_LAST, 0, 0, 0, ATREF_W, 1, 0, "S"},
{RULE_Syria, MON_OCT, FRI_LAST, 0, 0, 0, ATREF_W, 0, 0, ""},
{RULE_Thule, MON_MAR, SUN_GTEQ, 8, 2, 0, ATREF_W, 1, 0, "D"},
{RULE_Thule, MON_NOV, SUN_GTEQ, 1, 2, 0, ATREF_W, 0, 0, "S"},
{RULE_Tonga, MON_JAN, SUN_GTEQ, 15, 3, 0, ATREF_W, 0, 0, ""},
{RULE_Tonga, MON_NOV, SUN_GTEQ, 1, 2, 0, ATREF_W, 1, 0, "S"},
{RULE_Troll, MON_MAR, SUN_LAST, 0, 1, 0, ATREF_U, 2, 0, "+02"},
{RULE_Troll, MON_OCT, SUN_LAST, 0, 1, 0, ATREF_U, 0, 0, "+00"},
{RULE_US, MON_MAR, SUN_GTEQ, 8, 2, 0, ATREF_W, 1, 0, "D"},
{RULE_US, MON_NOV, SUN_GTEQ, 1, 2, 0, ATREF_W, 0, 0, "S"},
{RULE_WS, MON_APR, SUN_GTEQ, 1, 4, 0, ATREF_W, 0, 0, "S"},
{RULE_WS, MON_SEP, SUN_LAST, 0, 3, 0, ATREF_W, 1, 0, "D"},
{RULE_W_Eur, MON_MAR, SUN_LAST, 0, 1, 0, ATREF_S, 1, 0, "S"},
{RULE_W_Eur, MON_OCT, SUN_LAST, 0, 1, 0, ATREF_S, 0, 0, ""},
{RULE_Zion, MON_MAR, FRI_GTEQ, 23, 2, 0, ATREF_W, 1, 0, "D"},
{RULE_Zion, MON_OCT, SUN_LAST, 0, 2, 0, ATREF_W, 0, 0, "S"},
};
typedef struct {
	uint8_t zoneNameFromPrev : 5; // 0..31
	char zonename[21]; // Make the string live in ROM
	int8_t gmtoffhr   : 5; // -12...+12
	uint8_t gmtoffmin : 6; // 0..59
	uint8_t rule      : 6; // Empirical 44 rules
	char formatstr[12]; // Empirical lots of variation
} timezone_t;

static const timezone_t mtimezone[] ICACHE_RODATA_ATTR = {
{0, /*Africa/Abidjan*/ "Africa/Abidjan", 0, 0, RULE_NONE, "GMT"},
{8, /*Africa/Accra*/ "ccra", 0, 0, RULE_NONE, "%s"},
{8, /*Africa/Algiers*/ "lgiers", 1, 0, RULE_NONE, "CET"},
{7, /*Africa/Bissau*/ "Bissau", 0, 0, RULE_NONE, "GMT"},
{7, /*Africa/Cairo*/ "Cairo", 2, 0, RULE_NONE, "EE%sT"},
{9, /*Africa/Casablanca*/ "sablanca", 0, 0, RULE_Morocco, "WE%sT"},
{8, /*Africa/Ceuta*/ "euta", 1, 0, RULE_EU, "CE%sT"},
{7, /*Africa/El_Aaiun*/ "El_Aaiun", 0, 0, RULE_Morocco, "WE%sT"},
{7, /*Africa/Johannesburg*/ "Johannesburg", 2, 0, RULE_NONE, "SAST"},
{7, /*Africa/Khartoum*/ "Khartoum", 3, 0, RULE_NONE, "EAT"},
{7, /*Africa/Lagos*/ "Lagos", 1, 0, RULE_NONE, "WAT"},
{7, /*Africa/Maputo*/ "Maputo", 2, 0, RULE_NONE, "CAT"},
{8, /*Africa/Monrovia*/ "onrovia", 0, 0, RULE_NONE, "GMT"},
{7, /*Africa/Nairobi*/ "Nairobi", 3, 0, RULE_NONE, "EAT"},
{8, /*Africa/Ndjamena*/ "djamena", 1, 0, RULE_NONE, "WAT"},
{7, /*Africa/Tripoli*/ "Tripoli", 2, 0, RULE_NONE, "EET"},
{8, /*Africa/Tunis*/ "unis", 1, 0, RULE_NONE, "CE%sT"},
{7, /*Africa/Windhoek*/ "Windhoek", 1, 0, RULE_Namibia, "WA%sT"},
{1, /*America/Adak*/ "merica/Adak", -10, 0, RULE_US, "H%sT"},
{9, /*America/Anchorage*/ "nchorage", -9, 0, RULE_US, "AK%sT"},
{9, /*America/Araguaina*/ "raguaina", -3, 0, RULE_NONE, "-03"},
{10, /*America/Argentina/Buenos_Aires*/ "gentina/Buenos_Aires", -3, 0, RULE_NONE, "-03/-02"},
{18, /*America/Argentina/Catamarca*/ "Catamarca", -3, 0, RULE_NONE, "-03"},
{19, /*America/Argentina/Cordoba*/ "ordoba", -3, 0, RULE_NONE, "-03/-02"},
{18, /*America/Argentina/Jujuy*/ "Jujuy", -3, 0, RULE_NONE, "-03"},
{18, /*America/Argentina/La_Rioja*/ "La_Rioja", -3, 0, RULE_NONE, "-03"},
{18, /*America/Argentina/Mendoza*/ "Mendoza", -3, 0, RULE_NONE, "-03"},
{18, /*America/Argentina/Rio_Gallegos*/ "Rio_Gallegos", -3, 0, RULE_NONE, "-03"},
{18, /*America/Argentina/Salta*/ "Salta", -3, 0, RULE_NONE, "-03"},
{20, /*America/Argentina/San_Juan*/ "n_Juan", -3, 0, RULE_NONE, "-03"},
{22, /*America/Argentina/San_Luis*/ "Luis", -3, 0, RULE_NONE, "-03"},
{18, /*America/Argentina/Tucuman*/ "Tucuman", -3, 0, RULE_NONE, "-03/-02"},
{18, /*America/Argentina/Ushuaia*/ "Ushuaia", -3, 0, RULE_NONE, "-03"},
{9, /*America/Asuncion*/ "suncion", -4, 0, RULE_Para, "-04/-03"},
{9, /*America/Atikokan*/ "tikokan", -5, 0, RULE_NONE, "EST"},
{8, /*America/Bahia*/ "Bahia", -3, 0, RULE_NONE, "-03"},
{13, /*America/Bahia_Banderas*/ "_Banderas", -6, 0, RULE_Mexico, "C%sT"},
{10, /*America/Barbados*/ "rbados", -4, 0, RULE_NONE, "A%sT"},
{9, /*America/Belem*/ "elem", -3, 0, RULE_NONE, "-03"},
{11, /*America/Belize*/ "ize", -6, 0, RULE_NONE, "%s"},
{9, /*America/Blanc-Sablon*/ "lanc-Sablon", -4, 0, RULE_NONE, "AST"},
{9, /*America/Boa_Vista*/ "oa_Vista", -4, 0, RULE_NONE, "-04"},
{10, /*America/Bogota*/ "gota", -5, 0, RULE_NONE, "-05/-04"},
{10, /*America/Boise*/ "ise", -7, 0, RULE_US, "M%sT"},
{8, /*America/Cambridge_Bay*/ "Cambridge_Bay", -7, 0, RULE_Canada, "M%sT"},
{11, /*America/Campo_Grande*/ "po_Grande", -4, 0, RULE_Brazil, "-04/-03"},
{10, /*America/Cancun*/ "ncun", -5, 0, RULE_NONE, "EST"},
{10, /*America/Caracas*/ "racas", -4, 0, RULE_NONE, "-04"},
{10, /*America/Cayenne*/ "yenne", -3, 0, RULE_NONE, "-03"},
{9, /*America/Chicago*/ "hicago", -6, 0, RULE_US, "C%sT"},
{11, /*America/Chihuahua*/ "huahua", -7, 0, RULE_Mexico, "M%sT"},
{9, /*America/Costa_Rica*/ "osta_Rica", -6, 0, RULE_NONE, "C%sT"},
{9, /*America/Creston*/ "reston", -7, 0, RULE_NONE, "MST"},
{9, /*America/Cuiaba*/ "uiaba", -4, 0, RULE_Brazil, "-04/-03"},
{10, /*America/Curacao*/ "racao", -4, 0, RULE_NONE, "AST"},
{8, /*America/Danmarkshavn*/ "Danmarkshavn", 0, 0, RULE_NONE, "GMT"},
{10, /*America/Dawson*/ "wson", -8, 0, RULE_Canada, "P%sT"},
{14, /*America/Dawson_Creek*/ "_Creek", -7, 0, RULE_NONE, "MST"},
{9, /*America/Denver*/ "enver", -7, 0, RULE_US, "M%sT"},
{10, /*America/Detroit*/ "troit", -5, 0, RULE_US, "E%sT"},
{8, /*America/Edmonton*/ "Edmonton", -7, 0, RULE_Canada, "M%sT"},
{9, /*America/Eirunepe*/ "irunepe", -5, 0, RULE_NONE, "-05"},
{9, /*America/El_Salvador*/ "l_Salvador", -6, 0, RULE_NONE, "C%sT"},
{8, /*America/Fort_Nelson*/ "Fort_Nelson", -7, 0, RULE_NONE, "MST"},
{12, /*America/Fortaleza*/ "aleza", -3, 0, RULE_NONE, "-03"},
{8, /*America/Glace_Bay*/ "Glace_Bay", -4, 0, RULE_Canada, "A%sT"},
{9, /*America/Godthab*/ "odthab", -3, 0, RULE_EU, "-03/-02"},
{10, /*America/Goose_Bay*/ "ose_Bay", -4, 0, RULE_Canada, "A%sT"},
{9, /*America/Grand_Turk*/ "rand_Turk", -4, 0, RULE_NONE, "AST"},
{9, /*America/Guatemala*/ "uatemala", -6, 0, RULE_NONE, "C%sT"},
{11, /*America/Guayaquil*/ "yaquil", -5, 0, RULE_NONE, "-05/-04"},
{10, /*America/Guyana*/ "yana", -4, 0, RULE_NONE, "-04"},
{8, /*America/Halifax*/ "Halifax", -4, 0, RULE_Canada, "A%sT"},
{10, /*America/Havana*/ "vana", -5, 0, RULE_Cuba, "C%sT"},
{9, /*America/Hermosillo*/ "ermosillo", -7, 0, RULE_NONE, "MST"},
{8, /*America/Indiana/Indianapolis*/ "Indiana/Indianapolis", -5, 0, RULE_US, "E%sT"},
{16, /*America/Indiana/Knox*/ "Knox", -6, 0, RULE_US, "C%sT"},
{16, /*America/Indiana/Marengo*/ "Marengo", -5, 0, RULE_US, "E%sT"},
{16, /*America/Indiana/Petersburg*/ "Petersburg", -5, 0, RULE_US, "E%sT"},
{16, /*America/Indiana/Tell_City*/ "Tell_City", -6, 0, RULE_US, "C%sT"},
{16, /*America/Indiana/Vevay*/ "Vevay", -5, 0, RULE_US, "E%sT"},
{17, /*America/Indiana/Vincennes*/ "incennes", -5, 0, RULE_US, "E%sT"},
{16, /*America/Indiana/Winamac*/ "Winamac", -5, 0, RULE_US, "E%sT"},
{10, /*America/Inuvik*/ "uvik", -7, 0, RULE_Canada, "M%sT"},
{9, /*America/Iqaluit*/ "qaluit", -5, 0, RULE_Canada, "E%sT"},
{8, /*America/Jamaica*/ "Jamaica", -5, 0, RULE_NONE, "EST"},
{9, /*America/Juneau*/ "uneau", -9, 0, RULE_US, "AK%sT"},
{8, /*America/Kentucky/Louisville*/ "Kentucky/Louisville", -5, 0, RULE_US, "E%sT"},
{17, /*America/Kentucky/Monticello*/ "Monticello", -5, 0, RULE_US, "E%sT"},
{8, /*America/La_Paz*/ "La_Paz", -4, 0, RULE_NONE, "-04"},
{9, /*America/Lima*/ "ima", -5, 0, RULE_NONE, "-05/-04"},
{9, /*America/Los_Angeles*/ "os_Angeles", -8, 0, RULE_US, "P%sT"},
{8, /*America/Maceio*/ "Maceio", -3, 0, RULE_NONE, "-03"},
{10, /*America/Managua*/ "nagua", -6, 0, RULE_NONE, "C%sT"},
{12, /*America/Manaus*/ "us", -4, 0, RULE_NONE, "-04"},
{10, /*America/Martinique*/ "rtinique", -4, 0, RULE_NONE, "AST"},
{10, /*America/Matamoros*/ "tamoros", -6, 0, RULE_US, "C%sT"},
{10, /*America/Mazatlan*/ "zatlan", -7, 0, RULE_Mexico, "M%sT"},
{9, /*America/Menominee*/ "enominee", -6, 0, RULE_US, "C%sT"},
{10, /*America/Merida*/ "rida", -6, 0, RULE_Mexico, "C%sT"},
{10, /*America/Metlakatla*/ "tlakatla", -9, 0, RULE_US, "AK%sT"},
{10, /*America/Mexico_City*/ "xico_City", -6, 0, RULE_Mexico, "C%sT"},
{9, /*America/Miquelon*/ "iquelon", -3, 0, RULE_Canada, "-03/-02"},
{9, /*America/Moncton*/ "oncton", -4, 0, RULE_Canada, "A%sT"},
{11, /*America/Monterrey*/ "terrey", -6, 0, RULE_Mexico, "C%sT"},
{13, /*America/Montevideo*/ "video", -3, 0, RULE_NONE, "-03/-02"},
{8, /*America/Nassau*/ "Nassau", -5, 0, RULE_US, "E%sT"},
{9, /*America/New_York*/ "ew_York", -5, 0, RULE_US, "E%sT"},
{9, /*America/Nipigon*/ "ipigon", -5, 0, RULE_Canada, "E%sT"},
{9, /*America/Nome*/ "ome", -9, 0, RULE_US, "AK%sT"},
{10, /*America/Noronha*/ "ronha", -2, 0, RULE_NONE, "-02"},
{11, /*America/North_Dakota/Beulah*/ "th_Dakota/Beulah", -6, 0, RULE_US, "C%sT"},
{21, /*America/North_Dakota/Center*/ "Center", -6, 0, RULE_US, "C%sT"},
{21, /*America/North_Dakota/New_Salem*/ "New_Salem", -6, 0, RULE_US, "C%sT"},
{8, /*America/Ojinaga*/ "Ojinaga", -7, 0, RULE_US, "M%sT"},
{8, /*America/Panama*/ "Panama", -5, 0, RULE_NONE, "EST"},
{11, /*America/Pangnirtung*/ "gnirtung", -5, 0, RULE_Canada, "E%sT"},
{10, /*America/Paramaribo*/ "ramaribo", -3, 0, RULE_NONE, "-03"},
{9, /*America/Phoenix*/ "hoenix", -7, 0, RULE_NONE, "MST"},
{9, /*America/Port-au-Prince*/ "ort-au-Prince", -5, 0, RULE_NONE, "E%sT"},
{12, /*America/Port_of_Spain*/ "_of_Spain", -4, 0, RULE_NONE, "AST"},
{12, /*America/Porto_Velho*/ "o_Velho", -4, 0, RULE_NONE, "-04"},
{9, /*America/Puerto_Rico*/ "uerto_Rico", -4, 0, RULE_NONE, "AST"},
{10, /*America/Punta_Arenas*/ "nta_Arenas", -3, 0, RULE_NONE, "-03"},
{8, /*America/Rainy_River*/ "Rainy_River", -6, 0, RULE_Canada, "C%sT"},
{10, /*America/Rankin_Inlet*/ "nkin_Inlet", -6, 0, RULE_Canada, "C%sT"},
{9, /*America/Recife*/ "ecife", -3, 0, RULE_NONE, "-03"},
{10, /*America/Regina*/ "gina", -6, 0, RULE_NONE, "CST"},
{10, /*America/Resolute*/ "solute", -6, 0, RULE_Canada, "C%sT"},
{9, /*America/Rio_Branco*/ "io_Branco", -5, 0, RULE_NONE, "-05"},
{8, /*America/Santarem*/ "Santarem", -3, 0, RULE_NONE, "-03"},
{12, /*America/Santiago*/ "iago", -4, 0, RULE_Chile, "-04/-03"},
{12, /*America/Santo_Domingo*/ "o_Domingo", -4, 0, RULE_NONE, "AST"},
{10, /*America/Sao_Paulo*/ "o_Paulo", -3, 0, RULE_Brazil, "-03/-02"},
{9, /*America/Scoresbysund*/ "coresbysund", -1, 0, RULE_EU, "-01/+00"},
{9, /*America/Sitka*/ "itka", -9, 0, RULE_US, "AK%sT"},
{9, /*America/St_Johns*/ "t_Johns", -3, 30, RULE_Canada, "N%sT"},
{9, /*America/Swift_Current*/ "wift_Current", -6, 0, RULE_NONE, "CST"},
{8, /*America/Tegucigalpa*/ "Tegucigalpa", -6, 0, RULE_NONE, "C%sT"},
{9, /*America/Thule*/ "hule", -4, 0, RULE_Thule, "A%sT"},
{11, /*America/Thunder_Bay*/ "nder_Bay", -5, 0, RULE_Canada, "E%sT"},
{9, /*America/Tijuana*/ "ijuana", -8, 0, RULE_US, "P%sT"},
{9, /*America/Toronto*/ "oronto", -5, 0, RULE_Canada, "E%sT"},
{8, /*America/Vancouver*/ "Vancouver", -8, 0, RULE_Canada, "P%sT"},
{8, /*America/Whitehorse*/ "Whitehorse", -8, 0, RULE_Canada, "P%sT"},
{9, /*America/Winnipeg*/ "innipeg", -6, 0, RULE_Canada, "C%sT"},
{8, /*America/Yakutat*/ "Yakutat", -9, 0, RULE_US, "AK%sT"},
{9, /*America/Yellowknife*/ "ellowknife", -7, 0, RULE_Canada, "M%sT"},
{1, /*Antarctica/Casey*/ "ntarctica/Casey", 11, 0, RULE_NONE, "+11"},
{11, /*Antarctica/Davis*/ "Davis", 7, 0, RULE_NONE, "+07"},
{12, /*Antarctica/DumontDUrville*/ "umontDUrville", 10, 0, RULE_NONE, "+10"},
{11, /*Antarctica/Macquarie*/ "Macquarie", 11, 0, RULE_NONE, "+11"},
{13, /*Antarctica/Mawson*/ "wson", 5, 0, RULE_NONE, "+05"},
{11, /*Antarctica/Palmer*/ "Palmer", -3, 0, RULE_NONE, "-03"},
{11, /*Antarctica/Rothera*/ "Rothera", -3, 0, RULE_NONE, "-03"},
{11, /*Antarctica/Syowa*/ "Syowa", 3, 0, RULE_NONE, "+03"},
{11, /*Antarctica/Troll*/ "Troll", 0, 0, RULE_Troll, "%s"},
{11, /*Antarctica/Vostok*/ "Vostok", 6, 0, RULE_NONE, "+06"},
{1, /*Asia/Almaty*/ "sia/Almaty", 6, 0, RULE_NONE, "+06"},
{6, /*Asia/Amman*/ "mman", 2, 0, RULE_Jordan, "EE%sT"},
{6, /*Asia/Anadyr*/ "nadyr", 12, 0, RULE_NONE, "+12"},
{6, /*Asia/Aqtau*/ "qtau", 5, 0, RULE_NONE, "+05"},
{8, /*Asia/Aqtobe*/ "obe", 5, 0, RULE_NONE, "+05"},
{6, /*Asia/Ashgabat*/ "shgabat", 5, 0, RULE_NONE, "+05"},
{6, /*Asia/Atyrau*/ "tyrau", 5, 0, RULE_NONE, "+05"},
{5, /*Asia/Baghdad*/ "Baghdad", 3, 0, RULE_NONE, "+03/+04"},
{7, /*Asia/Baku*/ "ku", 4, 0, RULE_NONE, "+04/+05"},
{7, /*Asia/Bangkok*/ "ngkok", 7, 0, RULE_NONE, "+07"},
{7, /*Asia/Barnaul*/ "rnaul", 7, 0, RULE_NONE, "+07"},
{6, /*Asia/Beirut*/ "eirut", 2, 0, RULE_Lebanon, "EE%sT"},
{6, /*Asia/Bishkek*/ "ishkek", 6, 0, RULE_NONE, "+06"},
{6, /*Asia/Brunei*/ "runei", 8, 0, RULE_NONE, "+08"},
{5, /*Asia/Chita*/ "Chita", 9, 0, RULE_NONE, "+09"},
{7, /*Asia/Choibalsan*/ "oibalsan", 8, 0, RULE_NONE, "+08/+09"},
{6, /*Asia/Colombo*/ "olombo", 5, 30, RULE_NONE, "+0530"},
{5, /*Asia/Damascus*/ "Damascus", 2, 0, RULE_Syria, "EE%sT"},
{6, /*Asia/Dhaka*/ "haka", 6, 0, RULE_NONE, "+06/+07"},
{6, /*Asia/Dili*/ "ili", 9, 0, RULE_NONE, "+09"},
{6, /*Asia/Dubai*/ "ubai", 4, 0, RULE_NONE, "+04"},
{7, /*Asia/Dushanbe*/ "shanbe", 5, 0, RULE_NONE, "+05"},
{5, /*Asia/Famagusta*/ "Famagusta", 3, 0, RULE_NONE, "+03"},
{5, /*Asia/Gaza*/ "Gaza", 2, 0, RULE_Palestine, "EE%sT"},
{5, /*Asia/Hebron*/ "Hebron", 2, 0, RULE_Palestine, "EE%sT"},
{6, /*Asia/Ho_Chi_Minh*/ "o_Chi_Minh", 7, 0, RULE_NONE, "+07"},
{7, /*Asia/Hong_Kong*/ "ng_Kong", 8, 0, RULE_NONE, "HK%sT"},
{7, /*Asia/Hovd*/ "vd", 7, 0, RULE_NONE, "+07/+08"},
{5, /*Asia/Irkutsk*/ "Irkutsk", 8, 0, RULE_NONE, "+08"},
{5, /*Asia/Jakarta*/ "Jakarta", 7, 0, RULE_NONE, "WIB"},
{7, /*Asia/Jayapura*/ "yapura", 9, 0, RULE_NONE, "WIT"},
{6, /*Asia/Jerusalem*/ "erusalem", 2, 0, RULE_Zion, "I%sT"},
{5, /*Asia/Kabul*/ "Kabul", 4, 30, RULE_NONE, "+0430"},
{7, /*Asia/Kamchatka*/ "mchatka", 12, 0, RULE_NONE, "+12"},
{7, /*Asia/Karachi*/ "rachi", 5, 0, RULE_NONE, "PK%sT"},
{7, /*Asia/Kathmandu*/ "thmandu", 5, 45, RULE_NONE, "+0545"},
{6, /*Asia/Khandyga*/ "handyga", 9, 0, RULE_NONE, "+09"},
{6, /*Asia/Kolkata*/ "olkata", 5, 30, RULE_NONE, "IST"},
{6, /*Asia/Krasnoyarsk*/ "rasnoyarsk", 7, 0, RULE_NONE, "+07"},
{6, /*Asia/Kuala_Lumpur*/ "uala_Lumpur", 8, 0, RULE_NONE, "+08"},
{7, /*Asia/Kuching*/ "ching", 8, 0, RULE_NONE, "+08"},
{5, /*Asia/Macau*/ "Macau", 8, 0, RULE_NONE, "C%sT"},
{7, /*Asia/Magadan*/ "gadan", 11, 0, RULE_NONE, "+11"},
{7, /*Asia/Makassar*/ "kassar", 8, 0, RULE_NONE, "WITA"},
{7, /*Asia/Manila*/ "nila", 8, 0, RULE_NONE, "+08/+09"},
{5, /*Asia/Nicosia*/ "Nicosia", 2, 0, RULE_EUAsia, "EE%sT"},
{6, /*Asia/Novokuznetsk*/ "ovokuznetsk", 7, 0, RULE_NONE, "+07"},
{9, /*Asia/Novosibirsk*/ "sibirsk", 7, 0, RULE_NONE, "+07"},
{5, /*Asia/Omsk*/ "Omsk", 6, 0, RULE_NONE, "+06"},
{6, /*Asia/Oral*/ "ral", 5, 0, RULE_NONE, "+05"},
{5, /*Asia/Pontianak*/ "Pontianak", 7, 0, RULE_NONE, "WIB"},
{6, /*Asia/Pyongyang*/ "yongyang", 8, 30, RULE_NONE, "KST"},
{5, /*Asia/Qatar*/ "Qatar", 3, 0, RULE_NONE, "+03"},
{6, /*Asia/Qyzylorda*/ "yzylorda", 6, 0, RULE_NONE, "+06"},
{5, /*Asia/Riyadh*/ "Riyadh", 3, 0, RULE_NONE, "+03"},
{5, /*Asia/Sakhalin*/ "Sakhalin", 11, 0, RULE_NONE, "+11"},
{7, /*Asia/Samarkand*/ "markand", 5, 0, RULE_NONE, "+05"},
{6, /*Asia/Seoul*/ "eoul", 9, 0, RULE_NONE, "K%sT"},
{6, /*Asia/Shanghai*/ "hanghai", 8, 0, RULE_NONE, "C%sT"},
{6, /*Asia/Singapore*/ "ingapore", 8, 0, RULE_NONE, "+08"},
{6, /*Asia/Srednekolymsk*/ "rednekolymsk", 11, 0, RULE_NONE, "+11"},
{5, /*Asia/Taipei*/ "Taipei", 8, 0, RULE_NONE, "C%sT"},
{7, /*Asia/Tashkent*/ "shkent", 5, 0, RULE_NONE, "+05"},
{6, /*Asia/Tbilisi*/ "bilisi", 4, 0, RULE_NONE, "+04"},
{6, /*Asia/Tehran*/ "ehran", 3, 30, RULE_NONE, "+0330/+0430"},
{6, /*Asia/Thimphu*/ "himphu", 6, 0, RULE_NONE, "+06"},
{6, /*Asia/Tokyo*/ "okyo", 9, 0, RULE_NONE, "J%sT"},
{7, /*Asia/Tomsk*/ "msk", 7, 0, RULE_NONE, "+07"},
{5, /*Asia/Ulaanbaatar*/ "Ulaanbaatar", 8, 0, RULE_NONE, "+08/+09"},
{6, /*Asia/Urumqi*/ "rumqi", 6, 0, RULE_NONE, "+06"},
{6, /*Asia/Ust-Nera*/ "st-Nera", 10, 0, RULE_NONE, "+10"},
{5, /*Asia/Vladivostok*/ "Vladivostok", 10, 0, RULE_NONE, "+10"},
{5, /*Asia/Yakutsk*/ "Yakutsk", 9, 0, RULE_NONE, "+09"},
{7, /*Asia/Yangon*/ "ngon", 6, 30, RULE_NONE, "+0630"},
{6, /*Asia/Yekaterinburg*/ "ekaterinburg", 5, 0, RULE_NONE, "+05"},
{7, /*Asia/Yerevan*/ "revan", 4, 0, RULE_NONE, "+04/+05"},
{1, /*Atlantic/Azores*/ "tlantic/Azores", -1, 0, RULE_EU, "-01/+00"},
{9, /*Atlantic/Bermuda*/ "Bermuda", -4, 0, RULE_US, "A%sT"},
{9, /*Atlantic/Canary*/ "Canary", 0, 0, RULE_EU, "WE%sT"},
{11, /*Atlantic/Cape_Verde*/ "pe_Verde", -1, 0, RULE_NONE, "CVT"},
{9, /*Atlantic/Faroe*/ "Faroe", 0, 0, RULE_EU, "WE%sT"},
{9, /*Atlantic/Madeira*/ "Madeira", 0, 0, RULE_EU, "WE%sT"},
{9, /*Atlantic/Reykjavik*/ "Reykjavik", 0, 0, RULE_NONE, "GMT"},
{9, /*Atlantic/South_Georgia*/ "South_Georgia", -2, 0, RULE_NONE, "-02"},
{10, /*Atlantic/Stanley*/ "tanley", -3, 0, RULE_NONE, "-03"},
{1, /*Australia/Adelaide*/ "ustralia/Adelaide", 9, 30, RULE_AS, "AC%sT"},
{10, /*Australia/Brisbane*/ "Brisbane", 10, 0, RULE_NONE, "AE%sT"},
{12, /*Australia/Broken_Hill*/ "oken_Hill", 9, 30, RULE_AS, "AC%sT"},
{10, /*Australia/Currie*/ "Currie", 10, 0, RULE_AT, "AE%sT"},
{10, /*Australia/Darwin*/ "Darwin", 9, 30, RULE_NONE, "AC%sT"},
{10, /*Australia/Eucla*/ "Eucla", 8, 45, RULE_NONE, "+0845/+0945"},
{10, /*Australia/Hobart*/ "Hobart", 10, 0, RULE_AT, "AE%sT"},
{10, /*Australia/Lindeman*/ "Lindeman", 10, 0, RULE_NONE, "AE%sT"},
{11, /*Australia/Lord_Howe*/ "ord_Howe", 10, 30, RULE_LH, "+1030/+11"},
{10, /*Australia/Melbourne*/ "Melbourne", 10, 0, RULE_AV, "AE%sT"},
{10, /*Australia/Perth*/ "Perth", 8, 0, RULE_NONE, "AW%sT"},
{10, /*Australia/Sydney*/ "Sydney", 10, 0, RULE_AN, "AE%sT"},
{0, /*CET*/ "CET", 1, 0, RULE_C_Eur, "CE%sT"},
{1, /*CST6CDT*/ "ST6CDT", -6, 0, RULE_US, "C%sT"},
{0, /*EET*/ "EET", 2, 0, RULE_EU, "EE%sT"},
{1, /*EST*/ "ST", -5, 0, RULE_NONE, "EST"},
{3, /*EST5EDT*/ "5EDT", -5, 0, RULE_US, "E%sT"},
{1, /*Etc/GMT*/ "tc/GMT", 0, 0, RULE_NONE, "GMT"},
{7, /*Etc/GMT+1*/ "+1", -1, 0, RULE_NONE, "-01"},
{9, /*Etc/GMT+10*/ "0", -10, 0, RULE_NONE, "-10"},
{9, /*Etc/GMT+11*/ "1", -11, 0, RULE_NONE, "-11"},
{9, /*Etc/GMT+12*/ "2", -12, 0, RULE_NONE, "-12"},
{8, /*Etc/GMT+2*/ "2", -2, 0, RULE_NONE, "-02"},
{8, /*Etc/GMT+3*/ "3", -3, 0, RULE_NONE, "-03"},
{8, /*Etc/GMT+4*/ "4", -4, 0, RULE_NONE, "-04"},
{8, /*Etc/GMT+5*/ "5", -5, 0, RULE_NONE, "-05"},
{8, /*Etc/GMT+6*/ "6", -6, 0, RULE_NONE, "-06"},
{8, /*Etc/GMT+7*/ "7", -7, 0, RULE_NONE, "-07"},
{8, /*Etc/GMT+8*/ "8", -8, 0, RULE_NONE, "-08"},
{8, /*Etc/GMT+9*/ "9", -9, 0, RULE_NONE, "-09"},
{7, /*Etc/GMT-1*/ "-1", 1, 0, RULE_NONE, "+01"},
{9, /*Etc/GMT-10*/ "0", 10, 0, RULE_NONE, "+10"},
{9, /*Etc/GMT-11*/ "1", 11, 0, RULE_NONE, "+11"},
{9, /*Etc/GMT-12*/ "2", 12, 0, RULE_NONE, "+12"},
{9, /*Etc/GMT-13*/ "3", 13, 0, RULE_NONE, "+13"},
{9, /*Etc/GMT-14*/ "4", 14, 0, RULE_NONE, "+14"},
{8, /*Etc/GMT-2*/ "2", 2, 0, RULE_NONE, "+02"},
{8, /*Etc/GMT-3*/ "3", 3, 0, RULE_NONE, "+03"},
{8, /*Etc/GMT-4*/ "4", 4, 0, RULE_NONE, "+04"},
{8, /*Etc/GMT-5*/ "5", 5, 0, RULE_NONE, "+05"},
{8, /*Etc/GMT-6*/ "6", 6, 0, RULE_NONE, "+06"},
{8, /*Etc/GMT-7*/ "7", 7, 0, RULE_NONE, "+07"},
{8, /*Etc/GMT-8*/ "8", 8, 0, RULE_NONE, "+08"},
{8, /*Etc/GMT-9*/ "9", 9, 0, RULE_NONE, "+09"},
{4, /*Etc/UCT*/ "UCT", 0, 0, RULE_NONE, "UCT"},
{5, /*Etc/UTC*/ "TC", 0, 0, RULE_NONE, "UTC"},
{1, /*Europe/Amsterdam*/ "urope/Amsterdam", 1, 0, RULE_EU, "CE%sT"},
{8, /*Europe/Andorra*/ "ndorra", 1, 0, RULE_EU, "CE%sT"},
{8, /*Europe/Astrakhan*/ "strakhan", 4, 0, RULE_NONE, "+04"},
{8, /*Europe/Athens*/ "thens", 2, 0, RULE_EU, "EE%sT"},
{7, /*Europe/Belgrade*/ "Belgrade", 1, 0, RULE_EU, "CE%sT"},
{9, /*Europe/Berlin*/ "rlin", 1, 0, RULE_EU, "CE%sT"},
{8, /*Europe/Brussels*/ "russels", 1, 0, RULE_EU, "CE%sT"},
{8, /*Europe/Bucharest*/ "ucharest", 2, 0, RULE_EU, "EE%sT"},
{9, /*Europe/Budapest*/ "dapest", 1, 0, RULE_EU, "CE%sT"},
{7, /*Europe/Chisinau*/ "Chisinau", 2, 0, RULE_Moldova, "EE%sT"},
{8, /*Europe/Copenhagen*/ "openhagen", 1, 0, RULE_EU, "CE%sT"},
{7, /*Europe/Dublin*/ "Dublin", 0, 0, RULE_EU, "GMT/IST"},
{7, /*Europe/Gibraltar*/ "Gibraltar", 1, 0, RULE_EU, "CE%sT"},
{7, /*Europe/Helsinki*/ "Helsinki", 2, 0, RULE_EU, "EE%sT"},
{7, /*Europe/Istanbul*/ "Istanbul", 3, 0, RULE_NONE, "+03"},
{7, /*Europe/Kaliningrad*/ "Kaliningrad", 2, 0, RULE_NONE, "EET"},
{8, /*Europe/Kiev*/ "iev", 2, 0, RULE_EU, "EE%sT"},
{9, /*Europe/Kirov*/ "rov", 3, 0, RULE_NONE, "+03"},
{7, /*Europe/Lisbon*/ "Lisbon", 0, 0, RULE_EU, "WE%sT"},
{8, /*Europe/London*/ "ondon", 0, 0, RULE_EU, "GMT/BST"},
{8, /*Europe/Luxembourg*/ "uxembourg", 1, 0, RULE_EU, "CE%sT"},
{7, /*Europe/Madrid*/ "Madrid", 1, 0, RULE_EU, "CE%sT"},
{9, /*Europe/Malta*/ "lta", 1, 0, RULE_EU, "CE%sT"},
{8, /*Europe/Minsk*/ "insk", 3, 0, RULE_NONE, "+03"},
{8, /*Europe/Monaco*/ "onaco", 1, 0, RULE_EU, "CE%sT"},
{9, /*Europe/Moscow*/ "scow", 3, 0, RULE_NONE, "MSK"},
{7, /*Europe/Oslo*/ "Oslo", 1, 0, RULE_EU, "CE%sT"},
{7, /*Europe/Paris*/ "Paris", 1, 0, RULE_EU, "CE%sT"},
{8, /*Europe/Prague*/ "rague", 1, 0, RULE_EU, "CE%sT"},
{7, /*Europe/Riga*/ "Riga", 2, 0, RULE_EU, "EE%sT"},
{8, /*Europe/Rome*/ "ome", 1, 0, RULE_EU, "CE%sT"},
{7, /*Europe/Samara*/ "Samara", 4, 0, RULE_NONE, "+04"},
{9, /*Europe/Saratov*/ "ratov", 4, 0, RULE_NONE, "+04"},
{8, /*Europe/Simferopol*/ "imferopol", 3, 0, RULE_NONE, "MSK"},
{8, /*Europe/Sofia*/ "ofia", 2, 0, RULE_EU, "EE%sT"},
{8, /*Europe/Stockholm*/ "tockholm", 1, 0, RULE_EU, "CE%sT"},
{7, /*Europe/Tallinn*/ "Tallinn", 2, 0, RULE_EU, "EE%sT"},
{8, /*Europe/Tirane*/ "irane", 1, 0, RULE_EU, "CE%sT"},
{7, /*Europe/Ulyanovsk*/ "Ulyanovsk", 4, 0, RULE_NONE, "+04"},
{8, /*Europe/Uzhgorod*/ "zhgorod", 2, 0, RULE_EU, "EE%sT"},
{7, /*Europe/Vienna*/ "Vienna", 1, 0, RULE_EU, "CE%sT"},
{9, /*Europe/Vilnius*/ "lnius", 2, 0, RULE_EU, "EE%sT"},
{8, /*Europe/Volgograd*/ "olgograd", 3, 0, RULE_NONE, "+03"},
{7, /*Europe/Warsaw*/ "Warsaw", 1, 0, RULE_EU, "CE%sT"},
{7, /*Europe/Zaporozhye*/ "Zaporozhye", 2, 0, RULE_EU, "EE%sT"},
{8, /*Europe/Zurich*/ "urich", 1, 0, RULE_EU, "CE%sT"},
{0, /*HST*/ "HST", -10, 0, RULE_NONE, "HST"},
{0, /*Indian/Chagos*/ "Indian/Chagos", 6, 0, RULE_NONE, "+06"},
{9, /*Indian/Christmas*/ "ristmas", 7, 0, RULE_NONE, "+07"},
{8, /*Indian/Cocos*/ "ocos", 6, 30, RULE_NONE, "+0630"},
{7, /*Indian/Kerguelen*/ "Kerguelen", 5, 0, RULE_NONE, "+05"},
{7, /*Indian/Mahe*/ "Mahe", 4, 0, RULE_NONE, "SCT"},
{9, /*Indian/Maldives*/ "ldives", 5, 0, RULE_NONE, "+05"},
{9, /*Indian/Mauritius*/ "uritius", 4, 0, RULE_NONE, "MU%sT"},
{7, /*Indian/Reunion*/ "Reunion", 4, 0, RULE_NONE, "RET"},
{0, /*MET*/ "MET", 1, 0, RULE_C_Eur, "ME%sT"},
{1, /*MST*/ "ST", -7, 0, RULE_NONE, "MST"},
{3, /*MST7MDT*/ "7MDT", -7, 0, RULE_US, "M%sT"},
{0, /*PST8PDT*/ "PST8PDT", -8, 0, RULE_US, "P%sT"},
{1, /*Pacific/Apia*/ "acific/Apia", 13, 0, RULE_WS, "+13/+14"},
{9, /*Pacific/Auckland*/ "uckland", 12, 0, RULE_NZ, "NZ%sT"},
{8, /*Pacific/Bougainville*/ "Bougainville", 11, 0, RULE_NONE, "+11"},
{8, /*Pacific/Chatham*/ "Chatham", 12, 45, RULE_Chatham, "+1245/+1345"},
{10, /*Pacific/Chuuk*/ "uuk", 10, 0, RULE_NONE, "+10"},
{8, /*Pacific/Easter*/ "Easter", -6, 0, RULE_Chile, "-06/-05"},
{9, /*Pacific/Efate*/ "fate", 11, 0, RULE_NONE, "+11/+12"},
{9, /*Pacific/Enderbury*/ "nderbury", 13, 0, RULE_NONE, "+13"},
{8, /*Pacific/Fakaofo*/ "Fakaofo", 13, 0, RULE_NONE, "+13"},
{9, /*Pacific/Fiji*/ "iji", 12, 0, RULE_Fiji, "+12/+13"},
{9, /*Pacific/Funafuti*/ "unafuti", 12, 0, RULE_NONE, "+12"},
{8, /*Pacific/Galapagos*/ "Galapagos", -6, 0, RULE_NONE, "-06/-05"},
{10, /*Pacific/Gambier*/ "mbier", -9, 0, RULE_NONE, "-09"},
{9, /*Pacific/Guadalcanal*/ "uadalcanal", 11, 0, RULE_NONE, "+11"},
{11, /*Pacific/Guam*/ "m", 10, 0, RULE_NONE, "ChST"},
{8, /*Pacific/Honolulu*/ "Honolulu", -10, 0, RULE_NONE, "HST"},
{8, /*Pacific/Kiritimati*/ "Kiritimati", 14, 0, RULE_NONE, "+14"},
{9, /*Pacific/Kosrae*/ "osrae", 11, 0, RULE_NONE, "+11"},
{9, /*Pacific/Kwajalein*/ "wajalein", 12, 0, RULE_NONE, "+12"},
{8, /*Pacific/Majuro*/ "Majuro", 12, 0, RULE_NONE, "+12"},
{10, /*Pacific/Marquesas*/ "rquesas", -9, 30, RULE_NONE, "-0930"},
{8, /*Pacific/Nauru*/ "Nauru", 12, 0, RULE_NONE, "+12"},
{9, /*Pacific/Niue*/ "iue", -11, 0, RULE_NONE, "-11"},
{9, /*Pacific/Norfolk*/ "orfolk", 11, 0, RULE_NONE, "+11"},
{10, /*Pacific/Noumea*/ "umea", 11, 0, RULE_NONE, "+11/+12"},
{8, /*Pacific/Pago_Pago*/ "Pago_Pago", -11, 0, RULE_NONE, "SST"},
{10, /*Pacific/Palau*/ "lau", 9, 0, RULE_NONE, "+09"},
{9, /*Pacific/Pitcairn*/ "itcairn", -8, 0, RULE_NONE, "-08"},
{9, /*Pacific/Pohnpei*/ "ohnpei", 11, 0, RULE_NONE, "+11"},
{10, /*Pacific/Port_Moresby*/ "rt_Moresby", 10, 0, RULE_NONE, "+10"},
{8, /*Pacific/Rarotonga*/ "Rarotonga", -10, 0, RULE_NONE, "-10/-0930"},
{8, /*Pacific/Tahiti*/ "Tahiti", -10, 0, RULE_NONE, "-10"},
{10, /*Pacific/Tarawa*/ "rawa", 12, 0, RULE_NONE, "+12"},
{9, /*Pacific/Tongatapu*/ "ongatapu", 13, 0, RULE_Tonga, "+13/+14"},
{8, /*Pacific/Wake*/ "Wake", 12, 0, RULE_NONE, "+12"},
{10, /*Pacific/Wallis*/ "llis", 12, 0, RULE_NONE, "+12"},
{0, /*WET*/ "WET", 0, 0, RULE_EU, "WE%sT"},
};
typedef struct {
	uint8_t zoneNameFromPrev : 5; // 0..31
	char zonename[24]; // Make it live in ROM
	uint16_t timezone        : 9; // Empirical # of timezones < 511
} link_t;

static const link_t link[] ICACHE_RODATA_ATTR = {
{ 0, "Africa/Addis_Ababa", 13 /*Africa/Nairobi*/ },
{ 8, "smara", 13 /*Africa/Nairobi*/ },
{ 10, "era", 13 /*Africa/Nairobi*/ },
{ 7, "Bamako", 0 /*Africa/Abidjan*/ },
{ 9, "ngui", 10 /*Africa/Lagos*/ },
{ 10, "jul", 0 /*Africa/Abidjan*/ },
{ 8, "lantyre", 11 /*Africa/Maputo*/ },
{ 8, "razzaville", 10 /*Africa/Lagos*/ },
{ 8, "ujumbura", 11 /*Africa/Maputo*/ },
{ 7, "Conakry", 0 /*Africa/Abidjan*/ },
{ 7, "Dakar", 0 /*Africa/Abidjan*/ },
{ 9, "r_es_Salaam", 13 /*Africa/Nairobi*/ },
{ 8, "jibouti", 13 /*Africa/Nairobi*/ },
{ 8, "ouala", 10 /*Africa/Lagos*/ },
{ 7, "Freetown", 0 /*Africa/Abidjan*/ },
{ 7, "Gaborone", 11 /*Africa/Maputo*/ },
{ 7, "Harare", 11 /*Africa/Maputo*/ },
{ 7, "Juba", 9 /*Africa/Khartoum*/ },
{ 7, "Kampala", 13 /*Africa/Nairobi*/ },
{ 8, "igali", 11 /*Africa/Maputo*/ },
{ 9, "nshasa", 10 /*Africa/Lagos*/ },
{ 7, "Libreville", 10 /*Africa/Lagos*/ },
{ 8, "ome", 0 /*Africa/Abidjan*/ },
{ 8, "uanda", 10 /*Africa/Lagos*/ },
{ 9, "bumbashi", 11 /*Africa/Maputo*/ },
{ 9, "saka", 11 /*Africa/Maputo*/ },
{ 7, "Malabo", 10 /*Africa/Lagos*/ },
{ 9, "seru", 8 /*Africa/Johannesburg*/ },
{ 8, "babane", 8 /*Africa/Johannesburg*/ },
{ 8, "ogadishu", 13 /*Africa/Nairobi*/ },
{ 7, "Niamey", 10 /*Africa/Lagos*/ },
{ 8, "ouakchott", 0 /*Africa/Abidjan*/ },
{ 7, "Ouagadougou", 0 /*Africa/Abidjan*/ },
{ 7, "Porto-Novo", 10 /*Africa/Lagos*/ },
{ 7, "Sao_Tome", 0 /*Africa/Abidjan*/ },
{ 7, "Timbuktu", 0 /*Africa/Abidjan*/ },
{ 1, "merica/Anguilla", 120 /*America/Port_of_Spain*/ },
{ 10, "tigua", 120 /*America/Port_of_Spain*/ },
{ 9, "rgentina/ComodRivadavia", 22 /*America/Argentina/Catamarca*/ },
{ 10, "uba", 54 /*America/Curacao*/ },
{ 9, "tka", 18 /*America/Adak*/ },
{ 8, "Buenos_Aires", 21 /*America/Argentina/Buenos_Aires*/ },
{ 8, "Catamarca", 22 /*America/Argentina/Catamarca*/ },
{ 10, "yman", 115 /*America/Panama*/ },
{ 9, "oral_Harbour", 34 /*America/Atikokan*/ },
{ 11, "doba", 23 /*America/Argentina/Cordoba*/ },
{ 8, "Dominica", 120 /*America/Port_of_Spain*/ },
{ 8, "Ensenada", 141 /*America/Tijuana*/ },
{ 8, "Fort_Wayne", 75 /*America/Indiana/Indianapolis*/ },
{ 8, "Grenada", 120 /*America/Port_of_Spain*/ },
{ 9, "uadeloupe", 120 /*America/Port_of_Spain*/ },
{ 8, "Indianapolis", 75 /*America/Indiana/Indianapolis*/ },
{ 8, "Jujuy", 24 /*America/Argentina/Jujuy*/ },
{ 8, "Knox_IN", 76 /*America/Indiana/Knox*/ },
{ 9, "ralendijk", 54 /*America/Curacao*/ },
{ 8, "Louisville", 87 /*America/Kentucky/Louisville*/ },
{ 10, "wer_Princes", 54 /*America/Curacao*/ },
{ 8, "Marigot", 120 /*America/Port_of_Spain*/ },
{ 9, "endoza", 26 /*America/Argentina/Mendoza*/ },
{ 9, "ontreal", 142 /*America/Toronto*/ },
{ 12, "serrat", 120 /*America/Port_of_Spain*/ },
{ 8, "Porto_Acre", 129 /*America/Rio_Branco*/ },
{ 8, "Rosario", 23 /*America/Argentina/Cordoba*/ },
{ 8, "Santa_Isabel", 141 /*America/Tijuana*/ },
{ 9, "hiprock", 58 /*America/Denver*/ },
{ 9, "t_Barthelemy", 120 /*America/Port_of_Spain*/ },
{ 11, "Kitts", 120 /*America/Port_of_Spain*/ },
{ 11, "Lucia", 120 /*America/Port_of_Spain*/ },
{ 11, "Thomas", 120 /*America/Port_of_Spain*/ },
{ 11, "Vincent", 120 /*America/Port_of_Spain*/ },
{ 8, "Tortola", 120 /*America/Port_of_Spain*/ },
{ 8, "Virgin", 120 /*America/Port_of_Spain*/ },
{ 1, "ntarctica/McMurdo", 349 /*Pacific/Auckland*/ },
{ 11, "South_Pole", 349 /*Pacific/Auckland*/ },
{ 1, "rctic/Longyearbyen", 315 /*Europe/Oslo*/ },
{ 1, "sia/Aden", 212 /*Asia/Riyadh*/ },
{ 6, "shkhabad", 163 /*Asia/Ashgabat*/ },
{ 5, "Bahrain", 210 /*Asia/Qatar*/ },
{ 5, "Calcutta", 195 /*Asia/Kolkata*/ },
{ 6, "hongqing", 216 /*Asia/Shanghai*/ },
{ 7, "ungking", 216 /*Asia/Shanghai*/ },
{ 5, "Dacca", 176 /*Asia/Dhaka*/ },
{ 5, "Harbin", 216 /*Asia/Shanghai*/ },
{ 5, "Istanbul", 303 /*Europe/Istanbul*/ },
{ 5, "Kashgar", 227 /*Asia/Urumqi*/ },
{ 7, "tmandu", 193 /*Asia/Kathmandu*/ },
{ 6, "uwait", 212 /*Asia/Riyadh*/ },
{ 5, "Macao", 199 /*Asia/Macau*/ },
{ 6, "uscat", 178 /*Asia/Dubai*/ },
{ 5, "Phnom_Penh", 167 /*Asia/Bangkok*/ },
{ 5, "Rangoon", 231 /*Asia/Yangon*/ },
{ 5, "Saigon", 183 /*Asia/Ho_Chi_Minh*/ },
{ 5, "Tel_Aviv", 189 /*Asia/Jerusalem*/ },
{ 6, "himbu", 223 /*Asia/Thimphu*/ },
{ 5, "Ujung_Pandang", 201 /*Asia/Makassar*/ },
{ 6, "lan_Bator", 226 /*Asia/Ulaanbaatar*/ },
{ 5, "Vientiane", 167 /*Asia/Bangkok*/ },
{ 1, "tlantic/Faeroe", 238 /*Atlantic/Faroe*/ },
{ 9, "Jan_Mayen", 315 /*Europe/Oslo*/ },
{ 9, "St_Helena", 0 /*Africa/Abidjan*/ },
{ 1, "ustralia/ACT", 254 /*Australia/Sydney*/ },
{ 10, "Canberra", 254 /*Australia/Sydney*/ },
{ 10, "LHI", 251 /*Australia/Lord_Howe*/ },
{ 10, "NSW", 254 /*Australia/Sydney*/ },
{ 11, "orth", 247 /*Australia/Darwin*/ },
{ 10, "Queensland", 244 /*Australia/Brisbane*/ },
{ 10, "South", 243 /*Australia/Adelaide*/ },
{ 10, "Tasmania", 249 /*Australia/Hobart*/ },
{ 10, "Victoria", 252 /*Australia/Melbourne*/ },
{ 10, "West", 253 /*Australia/Perth*/ },
{ 10, "Yancowinna", 245 /*Australia/Broken_Hill*/ },
{ 0, "Brazil/Acre", 129 /*America/Rio_Branco*/ },
{ 7, "DeNoronha", 110 /*America/Noronha*/ },
{ 7, "East", 133 /*America/Sao_Paulo*/ },
{ 7, "West", 94 /*America/Manaus*/ },
{ 0, "Canada/Atlantic", 72 /*America/Halifax*/ },
{ 7, "Central", 145 /*America/Winnipeg*/ },
{ 7, "East-Saskatchewan", 127 /*America/Regina*/ },
{ 11, "ern", 142 /*America/Toronto*/ },
{ 7, "Mountain", 60 /*America/Edmonton*/ },
{ 7, "Newfoundland", 136 /*America/St_Johns*/ },
{ 7, "Pacific", 143 /*America/Vancouver*/ },
{ 7, "Saskatchewan", 127 /*America/Regina*/ },
{ 7, "Yukon", 144 /*America/Whitehorse*/ },
{ 1, "hile/Continental", 131 /*America/Santiago*/ },
{ 6, "EasterIsland", 353 /*Pacific/Easter*/ },
{ 1, "uba", 73 /*America/Havana*/ },
{ 0, "Egypt", 4 /*Africa/Cairo*/ },
{ 1, "ire", 300 /*Europe/Dublin*/ },
{ 1, "tc/GMT+0", 260 /*Etc/GMT*/ },
{ 7, "-0", 260 /*Etc/GMT*/ },
{ 7, "0", 260 /*Etc/GMT*/ },
{ 5, "reenwich", 260 /*Etc/GMT*/ },
{ 4, "Universal", 288 /*Etc/UTC*/ },
{ 4, "Zulu", 288 /*Etc/UTC*/ },
{ 1, "urope/Belfast", 308 /*Europe/London*/ },
{ 8, "ratislava", 317 /*Europe/Prague*/ },
{ 8, "usingen", 334 /*Europe/Zurich*/ },
{ 7, "Guernsey", 308 /*Europe/London*/ },
{ 7, "Isle_of_Man", 308 /*Europe/London*/ },
{ 7, "Jersey", 308 /*Europe/London*/ },
{ 7, "Ljubljana", 293 /*Europe/Belgrade*/ },
{ 7, "Mariehamn", 302 /*Europe/Helsinki*/ },
{ 7, "Nicosia", 203 /*Asia/Nicosia*/ },
{ 7, "Podgorica", 293 /*Europe/Belgrade*/ },
{ 7, "San_Marino", 319 /*Europe/Rome*/ },
{ 9, "rajevo", 293 /*Europe/Belgrade*/ },
{ 8, "kopje", 293 /*Europe/Belgrade*/ },
{ 7, "Tiraspol", 298 /*Europe/Chisinau*/ },
{ 7, "Vaduz", 334 /*Europe/Zurich*/ },
{ 9, "tican", 319 /*Europe/Rome*/ },
{ 7, "Zagreb", 293 /*Europe/Belgrade*/ },
{ 0, "GB", 308 /*Europe/London*/ },
{ 2, "-Eire", 308 /*Europe/London*/ },
{ 1, "MT", 260 /*Etc/GMT*/ },
{ 3, "+0", 260 /*Etc/GMT*/ },
{ 3, "-0", 260 /*Etc/GMT*/ },
{ 3, "0", 260 /*Etc/GMT*/ },
{ 1, "reenwich", 260 /*Etc/GMT*/ },
{ 0, "Hongkong", 184 /*Asia/Hong_Kong*/ },
{ 0, "Iceland", 240 /*Atlantic/Reykjavik*/ },
{ 1, "ndian/Antananarivo", 13 /*Africa/Nairobi*/ },
{ 7, "Comoro", 13 /*Africa/Nairobi*/ },
{ 7, "Mayotte", 13 /*Africa/Nairobi*/ },
{ 1, "ran", 222 /*Asia/Tehran*/ },
{ 1, "srael", 189 /*Asia/Jerusalem*/ },
{ 0, "Jamaica", 85 /*America/Jamaica*/ },
{ 2, "pan", 224 /*Asia/Tokyo*/ },
{ 0, "Kwajalein", 366 /*Pacific/Kwajalein*/ },
{ 0, "Libya", 15 /*Africa/Tripoli*/ },
{ 0, "Mexico/BajaNorte", 141 /*America/Tijuana*/ },
{ 11, "Sur", 97 /*America/Mazatlan*/ },
{ 7, "General", 101 /*America/Mexico_City*/ },
{ 0, "NZ", 349 /*Pacific/Auckland*/ },
{ 2, "-CHAT", 351 /*Pacific/Chatham*/ },
{ 1, "avajo", 58 /*America/Denver*/ },
{ 0, "PRC", 216 /*Asia/Shanghai*/ },
{ 1, "acific/Johnston", 363 /*Pacific/Honolulu*/ },
{ 8, "Midway", 373 /*Pacific/Pago_Pago*/ },
{ 8, "Ponape", 376 /*Pacific/Pohnpei*/ },
{ 8, "Saipan", 362 /*Pacific/Guam*/ },
{ 10, "moa", 373 /*Pacific/Pago_Pago*/ },
{ 8, "Truk", 352 /*Pacific/Chuuk*/ },
{ 8, "Yap", 352 /*Pacific/Chuuk*/ },
{ 1, "oland", 332 /*Europe/Warsaw*/ },
{ 2, "rtugal", 307 /*Europe/Lisbon*/ },
{ 0, "ROC", 219 /*Asia/Taipei*/ },
{ 2, "K", 215 /*Asia/Seoul*/ },
{ 0, "Singapore", 217 /*Asia/Singapore*/ },
{ 0, "Turkey", 303 /*Europe/Istanbul*/ },
{ 0, "UCT", 287 /*Etc/UCT*/ },
{ 1, "S/Alaska", 19 /*America/Anchorage*/ },
{ 5, "eutian", 18 /*America/Adak*/ },
{ 4, "rizona", 118 /*America/Phoenix*/ },
{ 3, "Central", 49 /*America/Chicago*/ },
{ 3, "East-Indiana", 75 /*America/Indiana/Indianapolis*/ },
{ 7, "ern", 107 /*America/New_York*/ },
{ 3, "Hawaii", 363 /*Pacific/Honolulu*/ },
{ 3, "Indiana-Starke", 76 /*America/Indiana/Knox*/ },
{ 3, "Michigan", 59 /*America/Detroit*/ },
{ 4, "ountain", 58 /*America/Denver*/ },
{ 3, "Pacific", 91 /*America/Los_Angeles*/ },
{ 10, "-New", 91 /*America/Los_Angeles*/ },
{ 3, "Samoa", 373 /*Pacific/Pago_Pago*/ },
{ 1, "TC", 288 /*Etc/UTC*/ },
{ 1, "niversal", 288 /*Etc/UTC*/ },
{ 0, "W-SU", 314 /*Europe/Moscow*/ },
{ 0, "Zulu", 288 /*Etc/UTC*/ },
};
